### PR TITLE
feat(config): make advanced SSH options configurable

### PR DESCRIPTION
**Pull request by adb-sh**
just found this quite useful for some vps providers
adds: `HostKeyAlgorithms`, `KeyExchanges`, `Ciphers` and `MAC` ssh args to yaml host config

### CODE REVIEW

**Comment by nicklasfrahm** [comment]
Didn't have time to deep dive into the code, but are these options just plain string arrays?

**Comment by adb-sh** [comment]
hey :)
yep, its just plain strings, string arrays. it literally just binds the `ssh.ClientConfig`-options to the yaml config

**Comment by nicklasfrahm** [comment]
Sorry for the delay. LGTM.

**Review by nicklasfrahm — APPROVED** [review]
LGTM.

**Pull request merged**
